require("core.plugin_config.catppuccin")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.mason")
require("core.plugin_config.lsp")
require("core.plugin_config.markdown-preview")
